name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore

      - name: Build and Lint (self-linting)
        run: dotnet build --no-restore --warnaserror

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack NoCommentsAnalyzer -c Release -o ./artifacts -p:Version=1.0.${{ github.run_number }}

      - name: Setup local NuGet source for package validation
        run: dotnet nuget add source ./artifacts --name local --store-password-in-clear-text

      - name: Validate package usage
        run: |
          cd ValidatePackage
          dotnet restore --source ../artifacts --source https://api.nuget.org/v3/index.json
          dotnet build --no-restore --warnaserror

      - name: Debug Ref
        run: echo "${{ github.ref }}"
      
      - name: List Artifacts
        run: ls -la ./artifacts
      
      - name: Publish to NuGet
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push ./artifacts/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
